version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  app:
    build:
      context: .
      target: development
    command: >
      sh -c "
        scripts/wait-for/wait-for postgres:5432 --
        scripts/wait-for/wait-for elasticmq:9324 --
        npm run migrate &&
        npm run start:watch"
    depends_on:
      - elasticmq
    ports:
      - "3003:3003"
