{{- include "ffc-helm-library.deployment" (list . "ffc-elm-scheme-service.deployment") -}}
{{- define "ffc-elm-scheme-service.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-elm-scheme-service.container") }}
{{- end -}}
