{{- if quote .Values.postgres.externalName }}
kind: Service
apiVersion: v1
metadata:
  name: {{ quote .Values.postgres.host }}
  namespace: {{ quote .Values.namespace }}
  labels: {{ include "ffc-elm.labels" . | trimSuffix "\n" | indent 2 }}
spec:
  type: ExternalName
  externalName: {{ quote .Values.postgres.externalName }}
  ports:
    - name: port
      port: {{ .Values.postgres.port }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.name }}
  namespace: {{ quote .Values.namespace }}
  labels: {{ include "ffc-elm.labels" . | trimSuffix "\n" | indent 2 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ quote .Values.namespace }}
    app.kubernetes.io/name: {{ quote .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ quote .Values.service.type }}
