# environment is the type of environment we're deploying to, e.g. "development" or "production"
environment: production
# image is the identifier for the Docker image to use for the main deployment
image: ffc-elm-plan-service
# name is the name to set in metadata for deployed resources
name: ffc-elm-plan-service
# namespace is the namespace to deploy into
namespace: ffc-elm
# workstream is the FFC workstream responsible for this deployment, used for rolebindings
workstream: ffc-elm

# deployment collects options for this chart's Deployment template
deployment:
  allowPrivilegeEscalation: false
  args: ["npm --no-update-notifier run migrate && node index"]
  command: ["/bin/sh","-c"]
  imagePullPolicy: Always
  limitCpu: 120m
  limitMemory: 120Mi
  maxSurge: 1
  maxUnavailable: 1
  minReadySeconds: 10
  priorityClassName: low
  readOnlyRootFilesystem: true
  redeployOnChange: update this field to force a change
  replicaCount: 1
  requestMemory: 60Mi
  requestCpu: 60m
  restartPolicy: Always
  runAsNonRoot: true
  runAsUser: 1000

# labels collects values for some standard labels to apply to deployed resources
labels:
  component: service
  instance: ""
  version: 1.0.0

# postgres collects connection details for interacting with the required Postgres database
postgres:
  database: ffc_elm_plan
  # postgres.externalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible at postgres.host
  externalName:
  host: ffc-elm-plan-postgres
  password: changeme
  username: postgres@ffc_elm_plan
  port: 5432

# probes collects liveness and readiness probe details for this chart's Deployment
probes:
  livenessProbe:
    path: /healthz
    port: 3003
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    path: /healthy
    port: 3003
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3

# queues collects connection details for interacting with required message queues
queues:
  planCommandQueue:
    accessKeyId: elasticmq
    create: true
    endpoint: http://ffc-elm-plan-message-queue:9324
    name: ffc-elm-plan-command
    region: eu-west-2
    secretAccessKey: elasticmq
    url: http://ffc-elm-plan-message-queue:9324/queue/ffc-elm-plan-command

# service collects options for this chart's main Service template
service:
  type: ClusterIP
  port: 80
